### ISSUE TITLE
Breaks when upgrading to Statamic v5.35.0

### ISSUE THREAD

**Issue by Jamesking56** [studio1902/statamic-peak-seo#47]
### Bug description

This addon causes the Collections page in the CP to throw an exception when upgrading from Statamic v5.35.0 and v5.36.0

### How to reproduce

- Install Statamic v5.35.0
- Install Peak SEO addon (latest version)
- Check Collections page in CP, all should work
- Upgrade to Statamic v5.36.0
- Collections page now throws an exception

### Logs

```shell
[2024-11-01 10:34:35] local.ERROR: Call to a member function inDefaultSite() on null {"userId":"ab670ce4-93cd-4405-a30d-194ab1ea44d6","exception":"[object] (Error(code: 0): Call to a member function inDefaultSite() on null at /home/jamesking56/PhpstormProjects/lafeef/vendor/studio1902/statamic-peak-seo/src/Actions/GenerateSocialImages.php:15)
[stacktrace]
#0 [internal function]: Studio1902\\PeakSeo\\Actions\\GenerateSocialImages->__construct()
#1 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Container/Container.php(983): ReflectionClass->newInstanceArgs()
#2 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\\Container\\Container->build()
#3 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\\Container\\Container->resolve()
#4 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\\Foundation\\Application->resolve()
#5 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\\Container\\Container->make()
#6 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(124): Illuminate\\Foundation\\Application->make()
#7 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Actions/ActionRepository.php(19): app()
#8 [internal function]: Statamic\\Actions\\ActionRepository->Statamic\\Actions\\{closure}()
#9 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map()
#10 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map()
#11 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Actions/ActionRepository.php(18): Illuminate\\Support\\Collection->map()
#12 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Actions/ActionRepository.php(25): Statamic\\Actions\\ActionRepository->all()
#13 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(358): Statamic\\Actions\\ActionRepository->for()
#14 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Controllers/CP/Collections/CollectionsController.php(70): Illuminate\\Support\\Facades\\Facade::__callStatic()
#15 [internal function]: Statamic\\Http\\Controllers\\CP\\Collections\\CollectionsController->Statamic\\Http\\Controllers\\CP\\Collections\\{closure}()
#16 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map()
#17 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map()
#18 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Controllers/CP/Collections/CollectionsController.php(55): Illuminate\\Support\\Collection->map()
#19 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Controllers/CP/Collections/CollectionsController.php(44): Statamic\\Http\\Controllers\\CP\\Collections\\CollectionsController->collections()
#20 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\CollectionsController->index()
#21 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#22 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#23 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#24 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#25 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#26 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle()
#28 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/AddVaryHeaderToResponse.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AddVaryHeaderToResponse->handle()
#30 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#32 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle()
#34 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle()
#36 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle()
#38 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/SelectedSite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\SelectedSite->handle()
#40 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\Localize->handle()
#42 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\Authorize->handle()
#44 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AddToasts->handle()
#48 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle()
#50 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle()
#52 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#54 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#56 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#58 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#60 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#62 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#63 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#65 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#67 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#69 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#71 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#72 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#73 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#74 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#75 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#76 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#78 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#80 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#82 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#84 /home/jamesking56/PhpstormProjects/lafeef/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#86 /home/jamesking56/PhpstormProjects/lafeef/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#88 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#90 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#91 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#93 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#95 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#96 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#97 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#98 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#99 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#100 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#101 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#102 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle()
#103 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#104 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#105 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#106 /home/jamesking56/PhpstormProjects/lafeef/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1188): Illuminate\\Foundation\\Http\\Kernel->handle()
#107 /home/jamesking56/PhpstormProjects/lafeef/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#108 /home/jamesking56/.config/composer/vendor/cpriego/valet-linux/server.php(239): require('...')
#109 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Lafeef
Laravel Version: 11.29.0
PHP Version: 8.3.12
Composer Version: 2.8.1
Environment: local
Debug Mode: ENABLED
URL: lafeef.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 2 (English, Arabic)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.36.0 PRO

Statamic Addons
jonassiewertsen/statamic-oh-dear: 1.11.0
reachweb/locale-lander: 3.0.0
studio1902/statamic-peak-seo: 8.16.0
takepart-media/statamic-oreos: 1.3.0
webographen/statamic-admin-log: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by robdekort** [comment]
Are you using Peak? It doesn't seem so. This addon is only intended for use with Peak.

**Comment by Jamesking56** [comment]
> Are you using Peak? It doesn't seem so. This addon is only intended for use with Peak.

Ah didn't realise it is dependent on a specific theme. Thank you

**Comment by robdekort** [comment]
No worries
